name: network_wrangler
channels:
  - defaults
  - conda-forge
dependencies:
  # Core Python
  - python=3.10.18
  - pip
  - setuptools
  - wheel
  
  # Jupyter and IPython
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  
  # Scientific computing
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - networkx
  
  # Plotting and visualization
  - matplotlib
  - seaborn
  - plotly
  - folium
  - branca
  
  # Geospatial
  - geopandas
  - mapclassify
  
  # Web and networking
  - requests
  - urllib3
  - charset-normalizer
  - idna
  
  # Data handling
  - h2
  - hpack
  - hyperframe
  - packaging
  - six
  - python-dateutil
  - pytz
  - python-tzdata
  - tzdata
  - zipp
  - importlib-metadata
  
  # Development tools
  - debugpy
  - decorator
  - executing
  - pure_eval
  - stack_data
  - traitlets
  - comm
  - nest-asyncio
  - psutil
  - tornado
  - pyzmq
  - platformdirs
  
  # Text processing
  - jinja2
  - markupsafe
  - pygments
  - prompt-toolkit
  - wcwidth
  - parso
  - jedi
  - pickleshare
  
  # Math and algorithms
  - cycler
  - kiwisolver
  - munkres
  - pyparsing
  - threadpoolctl
  - joblib
  
  # Compression and encoding
  - brotli
  - brotli-python
  - zstd
  - zstandard
  - lz4-c
  
  # System libraries
  - openssl
  - sqlite
  - tk
  - libffi
  - bzip2
  - xz
  - zlib
  - ca-certificates
  - certifi
  
  # Image processing
  - pillow
  - fonttools
  - freetype
  - libpng
  - jpeg
  - libtiff
  - openjpeg
  
  # Optional GUI (may not work in headless container)
  - qt-main
  
  # Typing and validation
  - typing_extensions
  - pycparser
  - cffi
  
  # Pip packages
  - pip:
      - annotated-types==0.7.0
      - attrs==25.3.0
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - fiona==1.10.1
      - geographiclib==2.1
      - geojson==3.2.0
      - geopandas==1.0.1
      - ijson==3.4.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - mypy-extensions==1.1.0
      - git+https://github.com/BayAreaMetro/network_wrangler.git
      - osmnx==2.0.6
      - pandera==0.26.1
      - projectcard==0.3.3
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyogrio==0.11.1
      - pyproj==3.7.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rpds-py==0.27.1
      - ruff==0.12.11
      - scipy==1.15.3
      - shapely==2.1.1
      - scikit-learn
      - pygris
      - tableauhyperapi==0.0.23135
      - tabulate==0.9.0
      - toml==0.10.2
      - typeguard==4.4.4
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1